[package]
name = "vst3-sys"
version = "0.1.0"
authors = ["Mike Hilgendorf <mike@hilgendorf.audio>", "Mirko Covizzi <mrkcvzz@gmail.com>"]
description = """
Pure Rust bindings to the VST3 APIs, based on COM. 
"""
edition = "2018"

[dependencies]
vst3-com = { path = "./com" }
bitflags = "1.2.0"

[dev-dependencies]
log = "0.4"
simple_logger = "1.6.0"
lazy_static = "1.4.0"
widestring = "0.4.0"

[workspace]
members = ["examples/again", "com", "com/macros", "com/macros/support"]

[[example]]
name = "passthru"
crate-type = ["cdylib"]
