[tasks.passthru]
workspace = false
script = []

[tasks.passthru.mac]
script = [
    "cargo build --example passthru", 
    "./osx-bundler.sh passthru target/debug/examples/libpassthru.dylib"
]

[tasks.passthru.linux]
workspace = false
script = [
    "cargo build --example passthru",
    "mkdir -p target/debug/plugin.vst3/Contents/x86_64-linux",
    "mkdir -p target/debug/plugin.vst3/Contents/Resources",
    "cp target/debug/examples/libpassthru.so target/debug/plugin.vst3/Contents/x86_64-linux/plugin.so"
]

[tasks.passthru.windows]
workspace = false
script_runner = "@shell"
script = [
    "cargo build --example passthru",
    "cp target/debug/examples/passthru.dll target/debug/passthru.vst3"
]

[tasks.again]
workspace = false
script = []

[tasks.again.mac]
workspace = false 
script = [
  "cargo build --package again",
  "./osx-bundler.sh again target/debug/libagain.dylib"
]

[tasks.again.linux]
workspace = false
script = [
    "cargo build --package again",
    "mkdir -p target/debug/plugin.vst3/Contents/x86_64-linux",
    "mkdir -p target/debug/plugin.vst3/Contents/Resources",
    "cp target/debug/libagain.so target/debug/plugin.vst3/Contents/x86_64-linux/plugin.so"
]

[tasks.again.windows]
workspace = false
script_runner = "@shell"
script = [
    "cargo build --package again",
    "cp target/debug/again.dll target/debug/again.vst3"
]
