mod ivstattributes;
mod ivstaudioprocessor;
mod ivstautomationstate;
mod ivstchannelcontextinfo;
mod ivstcomponent;
mod ivstcontextmenu;
mod ivsteditcontroller;
mod ivstevents;
mod ivstmessage;
mod ivstmidicontroller;
mod ivstmidilearn;
mod ivstnoteexpression;
mod ivstparameterchanges;
mod ivstphysicalui;
mod ivstpluginteracesupport;
mod ivstplugview;
mod ivstprefetchablesupport;
mod ivstprocesscontext;
mod ivstrepresentation;
mod ivstunits;
mod vstspeaker;
mod vsttypes;

pub use ivstattributes::*;
pub use ivstaudioprocessor::*;
pub use ivstautomationstate::*;
pub use ivstchannelcontextinfo::*;
pub use ivstcomponent::*;
pub use ivstcontextmenu::*;
pub use ivsteditcontroller::*;
pub use ivstevents::*;
pub use ivstmessage::*;
pub use ivstmidicontroller::*;
pub use ivstmidilearn::*;
pub use ivstnoteexpression::*;
pub use ivstparameterchanges::*;
pub use ivstphysicalui::*;
pub use ivstpluginteracesupport::*;
pub use ivstplugview::*;
pub use ivstprefetchablesupport::*;
pub use ivstprocesscontext::*;
pub use ivstrepresentation::*;
pub use ivstunits::*;
pub use vstspeaker::*;
pub use vsttypes::*;
// test/itest vstspeaker.h,
