on: 
  push: 
    branches: 
      - master 
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: formatting and linting
    steps:
      - name: checkout  
        uses: actions/checkout@v2
      - name: provision 
        uses: actions-rs/toolchain@v1 
        with: 
          toolchain: stable 
          profile: minimal
          components: rustfmt, clippy 
      - name: cargo fmt 
        uses: actions-rs/cargo@v1 
        with: 
          command: fmt 
          args: --all -- --check
      - name: cargo clippy  
        uses: actions-rs/cargo@v1 
        with: 
          command: clippy 
          args: --all-targets --all-features -- -D warnings

  validate:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        plugin: [again, passthru]
    runs-on: ${{ matrix.os }}
    name: validate
    steps:
      timeout-minutes: 10
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Make plugin
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ${{ matrix.plugin }}
      - name: Checkout steinbergmedia/vst3sdk
        uses: actions/checkout@v2
        with:
          repository: steinbergmedia/vst3sdk
          path: vst3sdk
          submodules: recursive
      - name: Compile validator (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: mkdir build && cd build && cmake -GXcode ../vst3sdk && cmake --build . --config Debug --target validator
      - name: Validate plugin (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: ./build/bin/Debug/validator target/debug/${{ matrix.plugin }}.vst3
      - name: Compile validator (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: mkdir build &&
          cd build && cmake -G "Visual Studio 16 2019" -A x64 ../vst3sdk &&
          cmake --build . --config Debug --target validator
      - name: Validate plugin (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\bin\Debug\validator target\debug\${{ matrix.plugin }}.vst3
      - name: Install validator dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install cmake gcc libstdc++6 libx11-xcb-dev libxcb-util-dev
          libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev
          libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
      - name: Compile validator (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mkdir build && cd build && cmake ../vst3sdk && cmake --build . --config Debug --target validator
      - name: Validate plugin (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./build/bin/Debug/validator target/debug/${{ matrix.plugin }}.vst3

  test: 
    strategy:
      matrix: 
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: test 
    steps:
    - uses: actions/checkout@v2 
    - uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable 
        profile: minimal  
    - uses: actions-rs/cargo@v1 
      with: 
        command: test 
        args: --all 